package main

import (
	"errors"
	"fmt"
	"os"

	"github.com/go-sql-driver/mysql"
	"github.com/jmoiron/sqlx"
	"github.com/makiuchi-d/migy/sqlfile"
	"github.com/makiuchi-d/testdb"
	"github.com/spf13/cobra"
)

var cmd = &cobra.Command{
	Use:           "migy",
	Short:         "A standalone database migration helper for MySQL",
	Long:          "",
	SilenceErrors: true,
	SilenceUsage:  true,
}

const signature = "-- Generated by migy (https://github.com/makiuchi-d/migy)"

var (
	targetDir string
	quit      bool
	migNumber int

	errInvalidDSNOrDumpfile = errors.New("invalid dsn form or dumpfile not found")
)

func init() {
	cmd.PersistentFlags().StringVarP(&targetDir, "dir", "d", ".", "directory with migration files")
	cmd.PersistentFlags().BoolVarP(&quit, "quit", "q", false, "quit stdout")
}

func main() {
	err := cmd.Execute()
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err.Error())
		os.Exit(-1)
	}
}

func warning(msg string) {
	fmt.Fprintln(os.Stderr, "warning:", msg)
}

func info(a ...any) {
	if quit {
		return
	}
	fmt.Fprintln(os.Stdout, a...)
}

func openDsnOrDumpfile(arg string) (*sqlx.DB, error) {
	if c, err := mysql.ParseDSN(arg); err == nil {
		c.ParseTime = true
		return sqlx.Open("mysql", c.FormatDSN())
	}

	db := sqlx.NewDb(testdb.New("db"), "mysql")
	if err := sqlfile.Apply(db, arg); err != nil {
		return nil, err
	}
	return db, nil
}
