-- Generated by migy (https://github.com/makiuchi-d/migy)
INSERT INTO _migrations (id, title, applied) VALUES (30, 'insert', now());
-- Write your forward migration SQL statements below.
INSERT INTO table1 (id, val, val2) VALUES
  (1, 'aaa', 10),
  (2, 'bbb', 200),
  (3, 'ccc', 30);
