-- Generated by migy (https://github.com/makiuchi-d/migy)
INSERT INTO _migrations (id, title, applied) VALUES (20, 'alter_add', now());
-- Write your forward migration SQL statements below.
ALTER TABLE table1 ADD COLUMN val2 int DEFAULT 0 AFTER val;
