-- Generated by migy (https://github.com/makiuchi-d/migy)
INSERT INTO _migrations (id, title, applied) VALUES (20, 'alter_users', now());
-- Write your forward migration SQL statements below.

ALTER TABLE `users` ADD COLUMN `email` VARCHAR(255);

UPDATE `users` SET `email` = 'user1@example.com' WHERE `id` = 1;
