-- Generated by migy (https://github.com/makiuchi-d/migy)
INSERT INTO _migrations (id, title, applied) VALUES (10, 'create_users', now());
-- Write your forward migration SQL statements below.

CREATE TABLE `users` (
  `id`   int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` varchar(255)
);

INSERT INTO `users` (`id`, `name`) VALUES (1, 'user1');
