-- Generated by migy (https://github.com/makiuchi-d/migy)
INSERT INTO _migrations (id, title, applied) VALUES (10, 'create', now());
-- Write your forward migration SQL statements below.
CREATE TABLE table1 (
  id  int NOT NULL,
  val text NOT NULL DEFAULT "",
  PRIMARY KEY (id)
);
