-- Generated by migy (https://github.com/makiuchi-d/migy)

CREATE TABLE `_migrations` (
  `id` int NOT NULL,
  `applied` datetime,
  `title` varchar(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

INSERT INTO `_migrations` (`id`,`applied`,`title`) VALUES
  (0, '2025-08-29 22:52:02', 'init'), (10, '2025-08-29 22:52:02', 'first'), (20, '2025-08-29 22:52:02', 'second'), (30, '2025-08-29 22:52:02', 'third');

DELIMITER //

CREATE PROCEDURE _migration_exists(IN input_id INTEGER)
BEGIN
  IF NOT EXISTS (SELECT 1 FROM _migrations WHERE id = input_id) THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'migration not found';
  END IF;
END//

DELIMITER ;
