-- Generated by migy (https://github.com/makiuchi-d/migy)
CALL _migration_exists(30);
DELETE FROM _migrations WHERE id = 30;
-- Write your rollback SQL statements below.
DELETE FROM table1 WHERE id IN (1, 3);
