-- Generated by migy (https://github.com/makiuchi-d/migy)
CALL _migration_exists(20);
DELETE FROM _migrations WHERE id = 20;
-- Write your rollback SQL statements below.
ALTER TABLE table1 DROP COLUMN val2;
