-- Generated by migy (https://github.com/makiuchi-d/migy)
CALL _migration_exists(40);
DELETE FROM _migrations WHERE id = 40;
-- Write your rollback SQL statements below.
ALTER TABLE table1 ADD COLUMN val text NOT NULL DEFAULT '' AFTER id;
