-- Generated by migy (https://github.com/makiuchi-d/migy)
INSERT INTO _migrations (id, title, applied) VALUES (40, 'alter_drop', now());
-- Write your forward migration SQL statements below.
ALTER TABLE table1 DROP COLUMN val;
