-- Generated by migy (https://github.com/makiuchi-d/migy)

CREATE TABLE `_migrations` (
  `id` int NOT NULL,
  `applied` datetime,
  `title` varchar(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

INSERT INTO `_migrations` (`id`,`applied`,`title`) VALUES
  (0, '2025-08-29 22:03:52', 'init'), (10, '2025-08-29 22:03:52', 'create'), (20, '2025-08-29 22:03:52', 'alter_add'), (30, '2025-08-29 22:03:56', 'insert'), (40, '2025-08-29 22:04:04', 'alter_drop'), (50, '2025-08-29 22:04:04', 'nothing');

CREATE TABLE `table1` (
  `id` int NOT NULL,
  `val2` int DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

INSERT INTO `table1` (`id`,`val2`) VALUES
  (1, 10), (2, 20), (3, 30);

DELIMITER //

CREATE PROCEDURE _migration_exists(IN input_id INTEGER)
BEGIN
  IF NOT EXISTS (SELECT 1 FROM _migrations WHERE id = input_id) THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'migration not found';
  END IF;
END//

DELIMITER ;
